version: "3.8"

services:
  web:
    build: .
    command:
      [
        "/wait-for.sh",
        "db",
        "5432",
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
      ]
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: uca_rec_user
      POSTGRES_PASSWORD: Elephant@123
      POSTGRES_DB: test
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
